spring:
  application:
    name: USER-SERVICE
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/microservice
    driverClassName: org.postgresql.Driver

  config:
    import: optional:configserver:http://localhost:8085

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka


management:
  health:
    circuitbreakers:
      enabled: true

  endpoints:
    web:
      exposure:
        include: health

  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      ratingHotelBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNoOfCalls: 5
        waitTimeInOpenState: 6s
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
        permittedNoOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenStateEnabled: trye
